// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdu8IW0lu6Sp0oMgR0qxVOu-FmWqviNM',
    appId: '1:189282985143:web:c510273d405a912a459932',
    messagingSenderId: '189282985143',
    projectId: 'shoppr-a294c',
    authDomain: 'shoppr-a294c.firebaseapp.com',
    storageBucket: 'shoppr-a294c.appspot.com',
    measurementId: 'G-PH7Y6H4KBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmF4Ev251Eb78Re9BjffADBM3Db9wAa2g',
    appId: '1:189282985143:android:9f97dae0c2c1e58a459932',
    messagingSenderId: '189282985143',
    projectId: 'shoppr-a294c',
    storageBucket: 'shoppr-a294c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Y4w8FQviJMnW_KvKFW7b_94USuFx0Hk',
    appId: '1:189282985143:ios:363ba5bcdf17e349459932',
    messagingSenderId: '189282985143',
    projectId: 'shoppr-a294c',
    storageBucket: 'shoppr-a294c.appspot.com',
    iosBundleId: 'com.example.shoppr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Y4w8FQviJMnW_KvKFW7b_94USuFx0Hk',
    appId: '1:189282985143:ios:4501e1b5493d28ab459932',
    messagingSenderId: '189282985143',
    projectId: 'shoppr-a294c',
    storageBucket: 'shoppr-a294c.appspot.com',
    iosBundleId: 'com.example.shoppr.RunnerTests',
  );
}
